name: Random Spawn
version: B1.9
main: me.Josvth.RandomSpawn.RandomSpawn
author: Josvth
commands:
  randomspawn:
    description: The main command.
    usage: Command not found! Try /rs help
    aliases: rs
  rs help:
    description: Shows a list with all the commands.
    usage: /rs help [1/2/3]
    permission: RandomSpawn.help
  rs reload:
    description: Reloads the Random Spawn config files.
    usage: /rs reload [config/worlds/spawnlocations]
    permission: RandomSpawn.reload
  rs info:
    description: Shows the Random Spawn settings for this world.
    usage: /rs info
    permission: RandomSpawn.info
  rs enable:
    description: Enables Random Spawn in this world.
    usage: /rs enable
    permission: RandomSpawn.configure
  rs disable:
    description: Disables Random Spawn in this world.
    usage: /rs disable
    permission: RandomSpawn.configure
  rs setarea:
    description: Sets the Random Spawn area.
    usage: /rs setarea [square/circle] <radius> or /rs setarea <xrange> <zrange> or /rs setarea <xmin> <xmax> <zmin> <zmax>
    permission: RandomSpawn.configure
  rs usebeds:
    description: Toggles using beds.
    usage: /rs usebeds [true/false]
    permission: RandomSpawn.configure
  rs keepfirstspawns:
    description: Toggles spawn saving.
    usage: /rs keepfirstspawns [true/false]
    aliases: kfs
    permission: RandomSpawn.configure
  rs firstjoin:
    description: Toggles randomspawning on first join.
    usage: /rs firstjoin [true/false]
    aliases: fj
    permission: RandomSpawn.configure
  rs setfirstspawn:
    description: Sets the first spawn location for this world.
    usage: /rs setfirstspawn
    aliases: sfs
    permission: RandomSpawn.setfirstspawn
  rs tpfirstspawn:
    description: Teleports you to the first spawn location of this world.
    usage: /rs tpfirstspawn
    aliases: tfs
    permission: RandomSpawn.tpfirstspawn
  rs unsetfirstspawn:
    description: Unsets the first spawn location for this world.
    usage: /rs unsetfirstspawn
    aliases: unsfs
    permission: RandomSpawn.setfirstspawn
    
permissions:
  RandomSpawn.*:
    description: Gives access to all Random Spawn commands.
    default: op
    children:
      RandomSpawn.configure: true
      RandomSpawn.help: true
      RandomSpawn.info: true
      RandomSpawn.placesign: true
  RandomSpawn.reload:
        description: Allows you to use the /rs reload command.
        default: op
  RandomSpawn.configure:
        description: Allows you to configure Random Spawn.
        default: op
        children:
          RandomSpawn.setfirstspawn: true
          RandomSpawn.teleporttofirstspawn: true
  RandomSpawn.help:
    description: Gives you access to the help commands.
    default: false
  RandomSpawn.info:
    description: Gives you access to the world info screen.
    default: true
  RandomSpawn.setfirstspawn:
        description: Allows you to use the /setfirstspawn command.
        default: op
  RandomSpawn.teleporttofirstspawn:
        description: Allows you to use the /tpfirstspawn command.
        default: op
  RandomSpawn.exclude:
        description: Excludes you from being randomly spawned.
        default: false
  RandomSpawn.placesign:
        description: Allows you to place Random Spawn Signs.
        default: op
  RandomSpawn.usesign:
        description: Allows you to use Random Spawn Signs.
        default: true